# railway.toml

# Nama proyek Railway
name = "Backend-berkah"

# Perintah untuk menjalankan aplikasi
[deploy]
  startCommand = "./main"
  restartPolicyType = "ALWAYS"
  restartPolicyMaxRetries = 5

# Variabel environment yang dibutuhkan untuk koneksi ke database
[variables]
  DB_USER = "root"
  DB_PASSWORD = "jumatberkah123"
  DB_HOST = "127.0.0.1"
  DB_PORT = "3306" # Ganti jika menggunakan port yang berbeda
  DB_NAME = "jumat_berkah"
  PORT = "8080" # Port default aplikasi
