# railway.toml

# Nama proyek Railway
name = "Backend-berkah"

# Entry point untuk deployment
[build]
  builder = "Docker" # Menggunakan Docker untuk membangun aplikasi

[deploy]
  startCommand = "./main" # Perintah untuk menjalankan aplikasi setelah deploy
  restartPolicyType = "ALWAYS" # Pastikan aplikasi selalu berjalan
  restartPolicyMaxRetries = 5  # Coba restart hingga 5 kali jika aplikasi gagal

# Variabel environment yang dibutuhkan untuk koneksi ke database
[variables]
  DB_USER = "root"
  DB_PASSWORD = "jumatberkah123"
  DB_HOST = "127.0.0.1"
  DB_PORT = "3306" # Ganti jika menggunakan port yang berbeda
  DB_NAME = "jumat_berkah"
  PORT = "8080" # Port default aplikasi
